[workspace]
resolver = "2"
members = [
    "backend",

    "frontend/user",
    "frontend/admin",
    "frontend/common",

    "communication"
]

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 1
