[workspace]
resolver = "2"
members = [
    "backend",
    "tls-proxy",

    "frontend",

    #Internal
    "common"
]

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 1
